//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conference
{
    using System;
    using System.Collections.Generic;
    
    public partial class conf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conf()
        {
            this.records = new HashSet<records>();
        }
    
        public int conf_id { get; set; }
        public string name { get; set; }
        public string subject { get; set; }
        public System.DateTime data { get; set; }
        public string place { get; set; }
        public int count_speakers { get; set; }
        public int count_guests { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<records> records { get; set; }
    }
}
